- name: Creating Redis repo
  ansible.builtin.shell: https://rpms.remirepo.net/enterprise/remi-release-8.rpm

- name: Enable DNF
  ansible.builtin.shell: dnf module enable redis:remi-6.2

- name: Install redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Change Ports
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start service Mongodb
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes