#print_head "Copying Mongo repo"
#cp ${script_location}/files/mongodb.repo /etc/yum.repos.d/mongodb.repo &>>${LOG}
#status_check
#
#print_head "Installing Mongodb"
#yum install mongodb-org -y &>>${LOG}
#status_check
#
#print_head "Starting Mongo service"
#systemctl enable mongod &>>${LOG}
#systemctl start mongod &>>${LOG}
#status_check
#
#print_head "changing Port adress"
#sed -i -e 's/127.0.0.1/0.0.0.0/gi' /etc/mongod.conf &>>${LOG}
#status_check
#
#print_head "Restart mongo"
#systemctl restart mongod &>>${LOG}
#status_check


- name: Copy file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongoDb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Start service Mongodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: Change Ports
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restart service
  ansible.builtin.service:
    name: mongod
    state: restarted
