- name: module disable
  ansible.builtin.shell: yum module disable mysql -y

- name: Copy file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install mysql
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: start service
  ansible.builtin.systemd:
    name: mysqld
    enabled: true
    state: started

- name: Set Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{mysql_password}}