- name: Install Mysql
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: Schema_load
  ansible.builtin.shell: mysql -h mysql-dev.ramdevops35.onlin e -uroot -p{{mysql_password}} < /app/schema/shipping.sql

- name: Restart service
  ansible.builtin.service:
    name: shipping
    state: restarted
