- name: Downloading Repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install Nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: AppPreReq
  ansible.builtin.include_tasks: appprereq.yml

- name: Install Npm
  community.general.npm:
    path: /app
    state: latest

- name: AppPreReq
  ansible.builtin.include_tasks: systemd.yml

- name: AppPreReq
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load

